apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"